"""GitLab automation helpers split into focused modules."""

from .constants import (
    GITLAB_DOMAIN,
    LOGIN_URL,
    SIGNUP_URL,
    DASHBOARD_URL,
    DASHBOARD_PROJECTS_URL,
    DASHBOARD_GROUPS_URL,
    PROFILE_URL,
    ACCOUNT_URL,
    SSH_KEYS_URL,
    ACCESS_TOKENS_URL,
    NEW_PROJECT_URL,
    NEW_GROUP_URL,
    get_project_url,
    get_project_issues_url,
    get_new_issue_url,
    get_issue_url,
    get_project_branches_url,
    get_new_branch_url,
    get_new_file_url,
    get_file_url,
    get_project_merge_requests_url,
    get_new_merge_request_url,
    get_merge_request_url,
    get_project_settings_url,
    get_group_url,
    get_group_members_url,
    get_group_settings_url,
    get_deploy_keys_url,
    get_deploy_tokens_url,
    get_webhooks_url,
    Selectors,
)
from .config import (
    DEFAULT_GITLAB_USERNAME,
    DEFAULT_GITLAB_PASSWORD,
    get_default_gitlab_credentials,
)
from .login import (
    LoginResult,
    login_user,
    is_logged_in,
)
from .issues import (
    Issue,
    CreateIssueResult,
    DeleteIssueResult,
    create_issue,
    create_issue_with_title,
    delete_issue,
    delete_issue_by_id,
    get_issues,
    delete_all_issues,
)
from .projects import (
    Project,
    CreateProjectResult,
    DeleteProjectResult,
    ForkProjectResult,
    create_private_project,
    fork_project,
    delete_project,
)
from .groups import (
    Group,
    GroupMember,
    CreateGroupResult,
    DeleteGroupResult,
    AddMemberResult,
    create_private_group,
    delete_group,
    get_group_members,
    add_member_to_group,
)
from .merge_requests import (
    MergeRequest,
    CreateMergeRequestResult,
    CloseMergeRequestResult,
    CommentMergeRequestResult,
    create_merge_request,
    close_merge_request,
    close_merge_request_by_url,
    get_mr_list,
    post_mr_comment,
)
from .branches import (
    Branch,
    CreateBranchResult,
    DeleteBranchResult,
    create_branch,
    delete_branch,
    get_branches,
)
from .files import (
    CreateFileResult,
    ReplaceFileResult,
    create_empty_file,
    create_file_with_content,
    replace_file_with_upload,
)
from .settings import (
    ProfileUpdateResult,
    UsernameChangeResult,
    DeleteResult,
    CreateAccessTokenResult,
    toggle_private_profile,
    change_username,
    delete_deploy_key,
    delete_deploy_token,
    delete_all_webhooks,
    delete_ssh_key,
    create_access_token,
    delete_all_access_tokens,
    delete_account,
)

__all__ = [
    # Constants
    "GITLAB_DOMAIN",
    "LOGIN_URL",
    "SIGNUP_URL",
    "DASHBOARD_URL",
    "DASHBOARD_PROJECTS_URL",
    "DASHBOARD_GROUPS_URL",
    "PROFILE_URL",
    "ACCOUNT_URL",
    "SSH_KEYS_URL",
    "ACCESS_TOKENS_URL",
    "NEW_PROJECT_URL",
    "NEW_GROUP_URL",
    "Selectors",
    # URL helpers
    "get_project_url",
    "get_project_issues_url",
    "get_new_issue_url",
    "get_issue_url",
    "get_project_branches_url",
    "get_new_branch_url",
    "get_new_file_url",
    "get_file_url",
    "get_project_merge_requests_url",
    "get_new_merge_request_url",
    "get_merge_request_url",
    "get_project_settings_url",
    "get_group_url",
    "get_group_members_url",
    "get_group_settings_url",
    "get_deploy_keys_url",
    "get_deploy_tokens_url",
    "get_webhooks_url",
    # Config
    "DEFAULT_GITLAB_USERNAME",
    "DEFAULT_GITLAB_PASSWORD",
    "get_default_gitlab_credentials",
    # Login
    "LoginResult",
    "login_user",
    "is_logged_in",
    # Issues
    "Issue",
    "CreateIssueResult",
    "DeleteIssueResult",
    "create_issue",
    "create_issue_with_title",
    "delete_issue",
    "delete_issue_by_id",
    "get_issues",
    "delete_all_issues",
    # Projects
    "Project",
    "CreateProjectResult",
    "DeleteProjectResult",
    "ForkProjectResult",
    "create_private_project",
    "fork_project",
    "delete_project",
    # Groups
    "Group",
    "GroupMember",
    "CreateGroupResult",
    "DeleteGroupResult",
    "AddMemberResult",
    "create_private_group",
    "delete_group",
    "get_group_members",
    "add_member_to_group",
    # Merge Requests
    "MergeRequest",
    "CreateMergeRequestResult",
    "CloseMergeRequestResult",
    "CommentMergeRequestResult",
    "create_merge_request",
    "close_merge_request",
    "close_merge_request_by_url",
    "get_mr_list",
    "post_mr_comment",
    # Branches
    "Branch",
    "CreateBranchResult",
    "DeleteBranchResult",
    "create_branch",
    "delete_branch",
    "get_branches",
    # Files
    "CreateFileResult",
    "ReplaceFileResult",
    "create_empty_file",
    "create_file_with_content",
    "replace_file_with_upload",
    # Settings
    "ProfileUpdateResult",
    "UsernameChangeResult",
    "DeleteResult",
    "CreateAccessTokenResult",
    "toggle_private_profile",
    "change_username",
    "delete_deploy_key",
    "delete_deploy_token",
    "delete_all_webhooks",
    "delete_ssh_key",
    "create_access_token",
    "delete_all_access_tokens",
    "delete_account",
]
