#!/usr/bin/env bash
set -euo pipefail

SERVER="$1"
TOTAL_WORKERS="$2"


FORWARD_SHOPPING=false
FORWARD_ADMIN=false
FORWARD_FORUM=false
FORWARD_GITLAB=true
FORWARD_WIKI=false

CMD=(ssh -N)

for WORKER_ID in $(seq 1 "$TOTAL_WORKERS"); do
  SHOPPING_REMOTE=$((7700 + WORKER_ID))
  ADMIN_REMOTE=$((7800 + WORKER_ID))
  FORUM_REMOTE=$((9900 + WORKER_ID))
  GITLAB_REMOTE=$((8023 + WORKER_ID))
  WIKI_REMOTE=$((8880 + WORKER_ID))
  SHOPPING_LOCAL=$((17700 + WORKER_ID))
  ADMIN_LOCAL=$((17800 + WORKER_ID))
  FORUM_LOCAL=$((19900 + WORKER_ID))
  GITLAB_LOCAL=$((18020 + WORKER_ID))
  WIKI_LOCAL=$((18880 + WORKER_ID))

  if $FORWARD_SHOPPING; then
    CMD+=(-L "${SHOPPING_LOCAL}:127.0.0.1:${SHOPPING_REMOTE}")
  fi

  if $FORWARD_ADMIN; then
    CMD+=(-L "${ADMIN_LOCAL}:127.0.0.1:${ADMIN_REMOTE}")
  fi

  if $FORWARD_FORUM; then
    CMD+=(-L "${FORUM_LOCAL}:127.0.0.1:${FORUM_REMOTE}")
  fi

  if $FORWARD_GITLAB; then
    CMD+=(-L "${GITLAB_LOCAL}:127.0.0.1:${GITLAB_REMOTE}")
  fi

  if $FORWARD_WIKI; then
    CMD+=(-L "${WIKI_LOCAL}:127.0.0.1:${WIKI_REMOTE}")
  fi
done

CMD+=("$SERVER")

exec "${CMD[@]}"


# exec ssh -N \
  # -L "${SHOPPING_LOCAL}:127.0.0.1:${SHOPPING_REMOTE}" \
  # -L "${ADMIN_LOCAL}:127.0.0.1:${ADMIN_REMOTE}" \
  # -L "${FORUM_LOCAL}:127.0.0.1:${FORUM_REMOTE}" \
  # -L "${GITLAB_LOCAL}:127.0.0.1:${GITLAB_REMOTE}" \
  # -L "${WIKI_LOCAL}:127.0.0.1:${WIKI_REMOTE}" \
  # "$SERVER"


  #ex: ./port_forwarding.sh annabella@red5k 5