"""
GitLab MCP Server — combined tool definitions.

Auto-generated by combine_tools.py
"""

import os
from urllib import response
import requests
from fastmcp import FastMCP, Context
import base64
from urllib.parse import quote
from typing import Any, Optional, Union, List, Dict
from servers.utils import truncate_mcp_response

# Initialize FastMCP server
mcp = FastMCP("GitLab API Server")

# Configuration
BASE_URL = os.getenv("GITLAB_BASE_URL", "http://127.0.0.1:8023").rstrip("/")
# API_PREFIX = "/api/v4"
DEFAULT_TIMEOUT = float(os.getenv("GITLAB_TIMEOUT", "30"))

# Store token for authenticated requests (global; shared across clients)
auth = {
    "token": os.getenv("GRAPHQL_TOKEN")  # loaded from .server_env via load_mcpserver_env()
}

def _graphql_request(
    query: str,
    variables: dict | None = None,
    token: Optional[str] = None,
) -> Any:
    """
    GraphQL helper: sends a GraphQL query to /api/graphql with Bearer token auth.
    """
    tok = token or auth.get("token")
    if not tok:
        raise ValueError("Missing GitLab token. Set GRAPHQL_TOKEN env var or call gitlab_set_token().")

    url = f"{BASE_URL}/api/graphql"
    headers = {
        "Authorization": f"Bearer {tok}",
        "Content-Type": "application/json"
    }

    payload = {"query": query}
    if variables:
        payload["variables"] = variables

    resp = requests.post(
        url,
        headers=headers,
        json=payload,
        timeout=DEFAULT_TIMEOUT,
    )
    resp.raise_for_status()
    return truncate_mcp_response(resp.json())

# --- Token management tools ---

@mcp.tool()
def gitlab_set_token(token: str) -> str:
    """Set (or replace) the GitLab token used by this server."""
    auth["token"] = token
    return "ok"

# --- GraphQL API Tools ---

@mcp.tool()
def get_current_user() -> Dict[str, Any]:
    """
    Get information about the currently authenticated GitLab user.

    Use this to verify authentication and retrieve the name of the user whose token is being used.
    Returns the user's display name from their GitLab profile.
    """
    query = "query { currentUser { name } }"
    return _graphql_request(query)

@mcp.tool()
def get_group_projects(full_path: str) -> Dict[str, Any]:
    """
    List all GitLab projects within a specific group or namespace.

    Use this to discover what projects exist under a group. Groups in GitLab are containers
    for multiple projects and subgroups. This returns the group ID, name, and a list of all
    project names within that group.

    Args:
        full_path: The full path of the group (e.g., 'gitlab-org', 'mycompany/engineering')
    """
    query = """
    query {
      group(fullPath: "%s") {
        id
        name
        projects {
          nodes {
            name
          }
        }
      }
    }
    """ % full_path
    return _graphql_request(query)

@mcp.tool()
def get_project_issue(full_path: str, iid: str) -> Dict[str, Any]:
    """
    Retrieve details about a specific issue from a GitLab project.

    Issues in GitLab are used for tracking bugs, feature requests, tasks, and discussions.
    This returns the project name and the issue title for the specified issue number.
    Use this when you need to look up a specific issue by its number.

    Args:
        full_path: The full path of the project (e.g., 'gitlab-org/graphql-sandbox', 'mycompany/myproject')
        iid: The issue number/internal ID visible in the GitLab UI (e.g., '2', '42')
    """
    query = """
    query {
      project(fullPath: "%s") {
        name
        issue(iid: "%s") {
          title
        }
      }
    }
    """ % (full_path, iid)
    return _graphql_request(query)

@mcp.tool()
def get_project_issues(full_path: str, first: Optional[int] = None, after: Optional[str] = None) -> Dict[str, Any]:
    """
    List all issues from a GitLab project with pagination support.

    Use this to browse all issues (bugs, tasks, feature requests) in a project. Returns issue
    titles and descriptions along with pagination information. Useful for getting an overview
    of open/closed issues in a project or finding issues that match certain criteria.

    Args:
        full_path: The full path of the project (e.g., 'gitlab-org/graphql-sandbox', 'mycompany/backend-api')
        first: Maximum number of issues to retrieve in this request (e.g., 10, 50)
        after: Pagination cursor from a previous request's pageInfo.endCursor to get the next page
    """
    pagination = ""
    if first is not None:
        pagination = f"first: {first}"
        if after:
            pagination += f', after: "{after}"'

    query = """
    query {
      project(fullPath: "%s") {
        name
        issues%s {
          nodes {
            title
            description
          }
          pageInfo {
            endCursor
            hasNextPage
          }
        }
      }
    }
    """ % (full_path, f"({pagination})" if pagination else "")
    return _graphql_request(query)

@mcp.tool()
def get_project_jobs(full_path: str) -> Dict[str, Any]:
    """
    Retrieve CI/CD pipeline jobs from a GitLab project.

    Jobs are individual tasks in GitLab CI/CD pipelines (like build, test, deploy steps).
    This returns job IDs and their execution durations. Use this to monitor pipeline performance,
    check job status, or troubleshoot CI/CD issues.

    Args:
        full_path: The full path of the project (e.g., 'gitlab-org/graphql-sandbox', 'myteam/webapp')
    """
    query = """
    query {
      project(fullPath: "%s") {
        jobs {
          nodes {
            id
            duration
          }
        }
      }
    }
    """ % full_path
    return _graphql_request(query)

@mcp.tool()
def add_emoji_reaction(awardable_id: str, emoji_name: str) -> Dict[str, Any]:
    """
    Add an emoji reaction (award) to a GitLab issue, merge request, or comment.

    GitLab allows users to react to content with emojis (similar to GitHub reactions).
    Use this to acknowledge, agree with, or react to issues, merge requests, or comments
    without writing a full comment. Common emojis: thumbsup, thumbsdown, heart, tada, rocket.

    Args:
        awardable_id: The global ID of the GitLab object (e.g., 'gid://gitlab/Issue/27039960', 'gid://gitlab/MergeRequest/123')
        emoji_name: The name of the emoji without colons (e.g., 'thumbsup', 'heart', 'tada', 'rocket')
    """
    query = """
    mutation {
      awardEmojiAdd(input: {
        awardableId: "%s",
        name: "%s"
      }) {
        awardEmoji {
          name
          description
          unicode
          emoji
          unicodeVersion
          user {
            name
          }
        }
        errors
      }
    }
    """ % (awardable_id, emoji_name)
    return _graphql_request(query)

@mcp.tool()
def create_comment(noteable_id: str, body: str) -> Dict[str, Any]:
    """
    Post a comment (note) on a GitLab issue, merge request, snippet, or commit.

    Comments in GitLab are called "notes" and can be added to various objects for discussion,
    feedback, or documentation. Use this to participate in issue discussions, review merge
    requests, or leave feedback on code. Supports markdown formatting.

    Args:
        noteable_id: The global ID of the GitLab object to comment on (e.g., 'gid://gitlab/Issue/27039960', 'gid://gitlab/MergeRequest/456')
        body: The markdown-formatted text content of your comment
    """
    # Escape quotes in the body
    escaped_body = body.replace('"', '\\"').replace('\n', '\\n')

    query = """
    mutation {
      createNote(input: {
        noteableId: "%s",
        body: "%s"
      }) {
        note {
          id
          body
          discussion {
            id
          }
        }
        errors
      }
    }
    """ % (noteable_id, escaped_body)
    return _graphql_request(query)

@mcp.tool()
def update_comment(note_id: str, body: str) -> Dict[str, Any]:
    """
    Edit an existing comment (note) on a GitLab issue, merge request, or other object.

    Use this to correct typos, update information, or revise your previous comments.
    Only the comment author or project maintainers can edit comments. The edit history
    is tracked in GitLab.

    Args:
        note_id: The global ID of the comment to edit (e.g., 'gid://gitlab/Note/123456')
        body: The new markdown-formatted text content to replace the existing comment
    """
    # Escape quotes in the body
    escaped_body = body.replace('"', '\\"').replace('\n', '\\n')

    query = """
    mutation {
      updateNote(input: {
        id: "%s",
        body: "%s"
      }) {
        note {
          id
          body
        }
        errors
      }
    }
    """ % (note_id, escaped_body)
    return _graphql_request(query)

@mcp.tool()
def delete_comment(note_id: str) -> Dict[str, Any]:
    """
    Permanently delete a comment (note) from a GitLab issue, merge request, or other object.

    Use this to remove inappropriate, outdated, or mistaken comments. Only the comment author
    or project maintainers can delete comments. This action cannot be undone.

    Args:
        note_id: The global ID of the comment to delete (e.g., 'gid://gitlab/Note/123456')
    """
    query = """
    mutation {
      destroyNote(input: { id: "%s" }) {
        note {
          id
          body
        }
        errors
      }
    }
    """ % note_id
    return _graphql_request(query)

@mcp.tool()
def get_issues_sorted(full_path: str, sort: str = "created_asc") -> Dict[str, Any]:
    """
    List GitLab project issues with custom sorting order.

    Use this to retrieve issues ordered by creation date or last update time, either ascending
    or descending. Helpful for finding the newest issues, oldest unresolved issues, or recently
    updated issues.

    Args:
        full_path: The full path of the project (e.g., 'gitlab-org/graphql-sandbox', 'company/product')
        sort: Sort order - 'created_asc' (oldest first), 'created_desc' (newest first), 'updated_asc', 'updated_desc'
    """
    query = """
    query {
      project(fullPath: "%s") {
        name
        issues(sort: %s) {
          nodes {
            title
            createdAt
          }
        }
      }
    }
    """ % (full_path, sort)
    return _graphql_request(query)

@mcp.tool()
def get_query_complexity(full_path: str) -> Dict[str, Any]:
    """
    Check GitLab GraphQL API query complexity score and limits.

    GitLab limits GraphQL query complexity to prevent abuse. Use this to understand how
    complex your queries are and what the maximum allowed complexity is. Helpful when
    debugging rate limiting or query failures.

    Args:
        full_path: The full path of any project to include in the test query (e.g., 'gitlab-org/gitlab')
    """
    query = """
    query {
      queryComplexity {
        score
        limit
      }
      project(fullPath: "%s") {
        name
      }
    }
    """ % full_path
    return _graphql_request(query)

# @mcp.tool()
# def get_schema_types() -> Dict[str, Any]:
#     """
#     Discover all available data types in the GitLab GraphQL API schema.

#     Use this for API exploration and to understand what types of objects and data structures
#     are available in the GitLab GraphQL API. Returns a list of all type names (like Issue,
#     Project, User, MergeRequest, etc.).
#     """
#     query = """
#     {
#       __schema {
#         types {
#           name
#         }
#       }
#     }
#     """
#     return _graphql_request(query)

# @mcp.tool()
# def get_type_info(type_name: str) -> Dict[str, Any]:
#     """
#     Get detailed schema information about a specific GitLab GraphQL type.

#     Use this to explore the structure of GitLab objects and understand what fields and
#     properties are available on types like Issue, Project, MergeRequest, User, etc.
#     Returns field names, descriptions, and data types for the specified type.

#     Args:
#         type_name: The name of the GraphQL type to inspect (e.g., 'Issue', 'Project', 'User', 'MergeRequest')
#     """
#     query = """
#     query IssueTypes {
#       __type(name: "%s") {
#         kind
#         name
#         fields {
#           name
#           description
#           type {
#             name
#           }
#         }
#       }
#     }
#     """ % type_name
#     return _graphql_request(query)

# @mcp.tool()
# def graphql_execute_custom_query(query: str, variables: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
#     """
#     Execute a custom GraphQL query or mutation.

#     Args:
#         query: The GraphQL query or mutation string
#         variables: Optional variables for the query
#     """
#     return _graphql_request(query, variables)



if __name__ == "__main__":
    # Run GitLab MCP server over HTTP (streamable-http transport) so the agent can connect via URL.
    #
    # IMPORTANT:
    # - This server URL (below) is NOT your GitLab instance URL.
    # - Your GitLab instance is at GITLAB_BASE_URL (default http://127.0.0.1:8023).
    # - The MCP server must listen on a DIFFERENT port than GitLab to avoid conflicts.
    from agent.common.configurator import Configurator
    from agent.common.utils import get_mcp_logger

    logger = get_mcp_logger()
    logger.debug("Starting gitlab-mcp server (streamable-http)")

    config = Configurator()
    config.load_server_env()
    config.load_shared_env()

    # Re-read the token now that .server_env has been loaded into the environment
    auth["token"] = os.getenv("GRAPHQL_TOKEN", auth.get("token"))

    # Read URL from config.yaml -> mcp_server.gitlab
    # Example: http://localhost:8001/
    mcp_server_url = config.get_key("mcp_server")["gitlab"]
    hostname, port, path = config.get_hostname_port(mcp_server_url)

    mcp.run(
        transport="streamable-http",
        host=hostname,
        port=port,
        path=path,
    )