"""Reddit automation helpers split into focused modules."""

from .constants import (
    REDDIT_DOMAIN,
    LOGIN_URL,
    REGISTRATION_URL,
    SUBMIT_URL,
    CREATE_FORUM_URL,
    MESSAGES_URL,
    Selectors,
    get_user_profile_url,
    get_user_account_url,
    get_user_block_list_url,
    get_block_user_url,
    get_compose_message_url,
    get_forum_url,
    get_post_url,
)
from .login import (
    LoginResult,
    UserCreationResult,
    login_user,
    create_user,
    is_logged_in,
)
from .posts import (
    Post,
    CreatePostResult,
    DeletePostResult,
    VotePostResult,
    EditPostResult,
    create_post,
    create_post_with_title_and_text,
    delete_post,
    delete_post_by_url,
    delete_all_posts_by_username,
    get_posts_by_username,
    vote_post,
    edit_post,
    get_forum_posts,
    get_post,
    search_posts,
)
from .forums import (
    Forum,
    CreateForumResult,
    SubscribeForumResult,
    create_forum,
    get_forum_info,
    forum_exists,
    subscribe_to_forum,
)
from .comments import (
    Comment,
    CommentResult,
    DeleteCommentResult,
    ReplyToCommentResult,
    comment_on_post,
    comment_on_post_by_url,
    delete_all_comments_on_post,
    delete_all_comments_on_post_by_user,
    get_comments_on_post,
    reply_to_comment,
)
from .messages import (
    Message,
    InboxMessage,
    MessageResult,
    DeleteMessagesResult,
    send_message,
    get_messages,
    delete_all_messages,
    delete_all_messages_by_user,
    get_message_threads,
)
from .users import (
    BlockUserResult,
    UnblockUserResult,
    ResetEmailResult,
    UpdateEmailResult,
    UserInfo,
    UpdateBiographyResult,
    block_user,
    unblock_user,
    reset_email,
    update_email,
    get_user_info,
    user_exists,
    get_blocked_users,
    update_biography,
)

__all__ = [
    # Constants
    "REDDIT_DOMAIN",
    "LOGIN_URL",
    "REGISTRATION_URL",
    "SUBMIT_URL",
    "CREATE_FORUM_URL",
    "MESSAGES_URL",
    "Selectors",
    # URL helpers
    "get_user_profile_url",
    "get_user_account_url",
    "get_user_block_list_url",
    "get_block_user_url",
    "get_compose_message_url",
    "get_forum_url",
    "get_post_url",
    # Login dataclasses
    "LoginResult",
    "UserCreationResult",
    # Login functions
    "login_user",
    "create_user",
    "is_logged_in",
    # Post dataclasses
    "Post",
    "CreatePostResult",
    "DeletePostResult",
    "VotePostResult",
    "EditPostResult",
    # Post functions
    "create_post",
    "create_post_with_title_and_text",
    "delete_post",
    "delete_post_by_url",
    "delete_all_posts_by_username",
    "get_posts_by_username",
    "vote_post",
    "edit_post",
    "get_forum_posts",
    "get_post",
    "search_posts",
    # Forum dataclasses
    "Forum",
    "CreateForumResult",
    "SubscribeForumResult",
    # Forum functions
    "create_forum",
    "get_forum_info",
    "forum_exists",
    "subscribe_to_forum",
    # Comment dataclasses
    "Comment",
    "CommentResult",
    "DeleteCommentResult",
    "ReplyToCommentResult",
    # Comment functions
    "comment_on_post",
    "comment_on_post_by_url",
    "delete_all_comments_on_post",
    "delete_all_comments_on_post_by_user",
    "get_comments_on_post",
    "reply_to_comment",
    # Message dataclasses
    "Message",
    "InboxMessage",
    "MessageResult",
    "DeleteMessagesResult",
    # Message functions
    "send_message",
    "get_messages",
    "delete_all_messages",
    "delete_all_messages_by_user",
    "get_message_threads",
    # User dataclasses
    "BlockUserResult",
    "UnblockUserResult",
    "ResetEmailResult",
    "UpdateEmailResult",
    "UserInfo",
    "UpdateBiographyResult",
    # User functions
    "block_user",
    "unblock_user",
    "reset_email",
    "update_email",
    "get_user_info",
    "user_exists",
    "get_blocked_users",
    "update_biography",
]
