# assume all env config files under project_root/config directory
client_env_path: config/.env
mcp_env_path: config/.mcpenv
shared_env_path: config/.sharedenv
server_env_path: config/.server_env

# agent_llm_provider: google-gla
# agent_llm_model: gemini-3-pro-preview
agent_llm_provider: anthropic
agent_llm_model: claude-sonnet-4-6
# agent_llm_model: claude-opus-4-6
# agent_llm_provider: openai
# agent_llm_model: gpt-5.4

# agent_llm_provider: google
# agent_llm_model: gemini-2.5-flash

llm_access_retry: 3

#higher temp more randomness (normal is ~0.2) lower more deterministics higher is more creative

llm_providers:
 openai:
  - model: gpt-5.4-mini
    temp: 0.0

  - model: gpt-5-mini
    temp: 0.0

  - model: gpt-5.4
    temp: 0.0

  - model: gpt-5.3-codex
    temp: 0.0

 anthropic:
  - model: claude-3-7-sonnet-20250219
    temp: 0.0

  - model: claude-opus-4-1-20250805
    temp: 0.0

  - model: claude-sonnet-4-0
    temp: 0.0

  - model: claude-sonnet-3-7
    temp: 0.0

  - model: claude-opus-4-6
    temp: 0.0

 google:
  - model: gemini-3-pro-preview
    temp: 0.0
  - model: gemini-3-flash-preview
    temp: 0.0
  - model: gemini-1.5-flash
    temp: 0.0
  - model: gemini-1.5-pro
    temp: 0.0


