"""Shared constants for the shipping_pw package."""

BASE_URL = "http://localhost:7770"
CART_URL = f"{BASE_URL}/checkout/cart/"
CHECKOUT_URL = f"{BASE_URL}/checkout/"
WISHLIST_URL = f"{BASE_URL}/wishlist/"
ACCOUNT_EDIT_URL = f"{BASE_URL}/customer/account/edit/"
ADDRESS_BOOK_URL = f"{BASE_URL}/customer/address/"
ORDER_HISTORY_URL = f"{BASE_URL}/sales/order/history/"
LOGIN_URL = f"{BASE_URL}/customer/account/login/"
